### ISSUE TITLE
Inline elements

### ISSUE THREAD

**Issue by lokithus** [Kinneyzhang/pp-html#1]
Hello, I have a question about this: How can you do inline elements? For example:

```
<p>This is a <em>text</em> inside a paragraph</p>
```

So far, I just pass the inline element as a string with the whole text, like this:

```
(pp-html '(p "This is a <em>text</em> inside a paragraph"))
```

But I would like to know if there is a better way to do it because I couldn't find a way to do it in the documentation. My knowledge of elisp is low but I want to use your package to practice elisp and html.

Thank you in advance.

**Comment by Kinneyzhang** [comment]
```emacs-lisp
(pp-html
 '(p "This is a " (em "text") "inside a paragraph"))
```
Just this.

**Comment by lokithus** [comment]
Thank you very much!
